FROM openjdk:11-jdk

# Set the working directory
WORKDIR /app

# Copy the JAR file from target folder to /app inside the conta>
COPY SPE_MINIPROJECT/demo/target/MiniProject-1.0-SNAPSHOT.jar app.jar

EXPOSE 8080

# Command to run the Java application
CMD ["java", "-jar", "app.jar"]
