---
- name: Pull Docker Image and Run Container
  hosts: localhost
  remote_user: kuldeepchamoli
  become: false

  tasks:
    - name: Pull Docker Image from Docker Hub
      docker_image:
        name: "kuldeep2026/calculator:latest"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Stop and remove old container (if exists)
      shell: docker rm -f calculator || true

    - name: Run the Docker container
      shell: docker run -d --name calculator -p 8080:8080 kuldeep2026/calculator:latest

